---
- name: "Update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 600

- name: "Install dependencies"
  apt:
    name:
      - tar
      - curl
      - gcc
      - wget
      - xz-utils
      - supervisor
      - libssl-dev
      - nginx
    state: present
