- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: "Init dependencies"
      include_tasks: init.yml

    - name: "Download & Set plasm node"
      include_tasks: plasm.yml

    - name: "Set Nginx & Configure SSL certs for WebSocket connections"
      include_tasks: ws.yml
