---
- name: "include var"
  include_vars: ../defaults/main.yml
- name: "create dir"
  command: "mkdir -p {{home_dir}}/{{src}}"

- name: "download binary"
  get_url:
    url: "https://github.com/staketechnologies/Plasm/releases/download/v1.7.0-dusty/plasm-node-ubuntu-1.7.0-x86_64.tar.xz"
    dest: "{{home_dir}}/{{src}}"
    force: false

- name: "unzip tar"
  command: "tar -xf plasm-node-ubuntu-1.7.0-x86_64.tar.xz"
  args:
    chdir: "{{home_dir}}/{{src}}"

- name: "start supervisor"
  command: "service supervisor start"

- name: "supervisor config"
  template:
    src: plasm.conf
    dest: /etc/supervisor/conf.d/plasm.conf

- name: "reread supervisor config"
  command: "supervisorctl reread"

- name: "update the supervisor config"
  command: "supervisorctl update"

- name: "start plasm node"
  command: "supervisorctl start all"
